"""add farmer ratings

Revision ID: 20cbfbd6d4e1
Revises: a55a9eb691e6
Create Date: 2026-09-14 20:47:45.967111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cbfbd6d4e1'
down_revision: Union[str, Sequence[str], None] = 'a55a9eb691e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('quality_accuracy', sa.Float(), nullable=False),
    sa.Column('communication', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('overall_rating', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_ratings_buyer_id'), 'farmer_ratings', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_farmer_ratings_farmer_id'), 'farmer_ratings', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_ratings_id'), 'farmer_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_ratings_id'), 'buyer_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_buyers_id'), 'buyers', ['id'], unique=False)
    op.create_index(op.f('ix_farmer_profiles_id'), 'farmer_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_logistics_options_id'), 'logistics_options', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_logistics_options_id'), table_name='logistics_options')
    op.drop_index(op.f('ix_farmer_profiles_id'), table_name='farmer_profiles')
    op.drop_index(op.f('ix_buyers_id'), table_name='buyers')
    op.drop_index(op.f('ix_buyer_ratings_id'), table_name='buyer_ratings')
    op.drop_index(op.f('ix_farmer_ratings_id'), table_name='farmer_ratings')
    op.drop_index(op.f('ix_farmer_ratings_farmer_id'), table_name='farmer_ratings')
    op.drop_index(op.f('ix_farmer_ratings_buyer_id'), table_name='farmer_ratings')
    op.drop_table('farmer_ratings')
    # ### end Alembic commands ###
